title: PSICOMP
apply_href: https://docs.google.com/a/princeton.edu/forms/d/e/1FAIpQLSe9ROhZyP1aN-jcvXEQbbeuvT-b0dKmZP0Lnqi3O44l0xTlsQ/viewform
description: PSICOMP (Princeton Social Impact Competition) is Princeton University’s annual social venture competition hosted by Princeton Social Innovation.
